// <auto-generated />
namespace may222017.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class votelogupdatemigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(votelogupdatemigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201705251451428_votelogupdate-migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
